name: Build packages

on:
    workflow_dispatch:
    push:
        branches:
            - ci

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Init environment
              run: make init

            - name: Build packages
              run: make -j$(nproc)

            - name: Upload artifacts
              uses: actions/upload-artifact@v7
              with:
                name: build-artifacts
                path: |
                    *.deb
                    *.buildinfo
                    *.changes
                    *.dsc
                    *.build
                    *.source.changes
                    *.orig.tar.gz
                    *.debian.tar.xz
                    *.tar.gz
                    *.tar.xz
