name: Build Debian packages

on:
    workflow_dispatch:
    push:
        branches:
            - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-22.04
        container:
          image: alkosenko/openfix-debian-ci:ci
          options: --privileged
        env:
          BASE_PATH: ${{ github.workspace }}/.cowbuilder/base.cow
          APT_CACHE_PATH: ${{ github.workspace }}/.aptcache
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Trust git repository
              run: git config --global --add safe.directory '*'

            - name: Init environment
              run: make init

            - name: Build packages
              run: make -j$(nproc)

            - name: Upload artifacts
              uses: actions/upload-artifact@v7
              with:
                name: build-artifacts
                path: &artifacts |
                    *.deb
                    *.buildinfo
                    *.changes
                    *.dsc
                    *.build
                    *.tar.gz
                    *.tar.xz

            - name: Short SHA
              id: short-sha
              run: echo "sha16=$(git rev-parse --short=16 HEAD)" >> $GITHUB_OUTPUT

            - name: Create tag
              if: github.ref == 'refs/heads/master'
              run: |
                git tag ${{ steps.short-sha.outputs.sha16 }}
                git push origin ${{ steps.short-sha.outputs.sha16 }}

            - name: Create GitHub release
              if: github.ref == 'refs/heads/master'
              uses: softprops/action-gh-release@v2
              with:
                name: ${{ steps.short-sha.outputs.sha16 }}
                tag_name: ${{ steps.short-sha.outputs.sha16 }}
                prerelease: false
                make_latest: true
                generate_release_notes: true
                fail_on_unmatched_files: false
                files: *artifacts

